import type { NextPage } from 'next'
import Head from 'next/head'

const Cart: NextPage = () => {
  return(
    <>
      <Head>
        <title>Carrinho</title>
        <meta name='discription' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
        <h1>
          Carrinho
        </h1>
    </>
  );
}

export default Cart;