import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='discription' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <main>
        <h1>
          welcome to <a href='https://nextjs.org' target='_blank'>Next.js!</a>
        </h1>
        <p>
          lorem ipsum dolor, sit amet consectetur  adiscripklsdj elit. Sit error!
        </p>
      </main>
    </>
  );
}

export default Home;